### ISSUE TITLE
Poor performance when using videos from other datasets

### ISSUE THREAD

**Issue by JSHZT** [Vision-CAIR/MiniGPT4-video#33]
I used the video from vgg-sound, I used the default question, but I found that the answer from minigpt4-video has nothing to do with the video.

**Comment by KerolosAtef** [comment]
Thanks for your feedback 
I discovered a bug related to hallucinations in MiniGPT4-video yesterday. It seems to be connected to the PEFT library. I was initially using PEFT 0.2.0, but after upgrading, the function `prepare_model_for_int8_training` was deprecated. When I switched to `prepare_model_for_kbit_training`, a significant increase in hallucinations occurred. 
Keep this in mind to ensure accurate performance.
It solved in the current version

**Comment by JSHZT** [comment]
I use question："Please describe the content of the video **only** in the following format: 'This video describes [video content], where [subject] appears doing [actions] in [setting/scenery].' Do not provide any additional information or explanations." but the result still cannot get the correct video information. The video I input is a video from the vgg_sound dataset, which is 10 seconds long. Are there any other good usage suggestions?
